[env:esp32-s3-devkitc-1]
platform = espressif32
board = esp32-s3-devkitc-1
framework = arduino
monitor_speed = 115200
upload_speed = 921600
extra_scripts = pre:scripts/remove_map_file.py

lib_deps =
  adafruit/Adafruit SHT31 Library
  adafruit/Adafruit GFX Library
  adafruit/Adafruit ST7735 and ST7789 Library
  ricmoo/QRCode
